### ISSUE TITLE
Feature request: Multiple "word" --> color options

### ISSUE THREAD

**Issue by Mallardbro** [Alexsuperfly/RuneLite-Hub-Plugins#1]
It would be cool to have multiple filters matched up to individual colors.

Example...

Filter1 = "compost"  -->  Color1 = "purple"
Filter2 = "Farming Guild Contract"  -->  Color2 = "green"
Filter3 = "inventory, interesting"  -->  Color3 = "red"

I would naively say this is almost just adding a loop to the current code.

Thanks!

**Comment by Alexsuperfly** [comment]
added in v1.1
