### ISSUE TITLE
Not matching some trade requests with too many spaces

### ISSUE THREAD

**Issue by Conrad33** [Alexsuperfly/RuneLite-Hub-Plugins#2]
My buddy and I were trying to use this plugin to change the color of each other's trade requests so we know its actually us trading each other. I can match his name fine, ie "[name] wishes to trade with you." But my name is unable to be matched. My in game name is single characters separated by spaces ie "n a m e". For some reason this cannot be matched on a trade request, yet it can be matched if i type out my name into the public chat.

**Comment by Alexsuperfly** [comment]
I've just had an update merged that I believe solves this, could you check now.  You'll want to update the plugin manually in the hub interface or restart the client to make sure you've pulled the latest changes

**Comment by Alexsuperfly** [comment]
closing as stale and assumed fixed
