### ISSUE TITLE
Force chat recolor

### ISSUE THREAD

**Issue by otygah** [Alexsuperfly/RuneLite-Hub-Plugins#3]
Chat recolor plugin does not appear to work for runelite-generated game messages:
Example - trying to set up custom colour for 'You have low prayer!' runelite game message, although it doesn't override the default red colour the client provides. Also tried enabling 'match all message types'  box
Awesome plugin btw

**Comment by Alexsuperfly** [comment]
are you putting the `!` in the matching words box, if so do not do that.  Otherwise this would be because the notifier might not be posting an event for the message being sent.

**Comment by otygah** [comment]
Unfortunately after removing the ! the issue is still there.

**Comment by Alexsuperfly** [comment]
I did some looking into it and its actually replacing the message formatting like it should but its just not working with messages sent by the notifier, and i currently have no idea why

**Comment by Alexsuperfly** [comment]
I found out that RuneLite generated messages seem to fire off the chat message event before they change the content for the final time themselves, overriding what this plugin edits them to.  I make a change to correct that and it will be available in v1.3.1 of the plugin.
